<?php
// Staging wp-config.php — generated by assistant; replace salts with fresh values

/** The name of the database for WordPress */
define('DB_NAME', 'pools425_wp872');
/** Database username */
define('DB_USER', 'pools425_wp872');
/** Database password */
define('DB_PASSWORD', 'p7SFK)8X@3');
/** Database hostname */
define('DB_HOST', 'localhost');
/** Database charset to use in creating database tables. */
define('DB_CHARSET', 'utf8');
/** The database collate type. Don't change this if in doubt. */
define('DB_COLLATE', '');

/**#@+
define('AUTH_KEY',         'pIypEqMyXaT$/-9|ekocoA%_ri5-B;+IePq/!Q<q@&|[#99PQyo3rl#&y%S_47B[');
define('SECURE_AUTH_KEY',  '2@CwZ<o.foe0W^RMn3S_eJ*2ek_XhOA-#|bJtP@Pov~8X|h90.9k%x+9t:{NG]f`');
define('LOGGED_IN_KEY',    'r-=,4&!n8]BM|LfBQ*u_qk3Q*eEB=Vt<F#?h<}r:k6HE0kCLjdFm~gdU>y{S}XT~');
define('NONCE_KEY',        '9{ub}}~NDCGJ|0#l6X4})EZ9y~wt=,T1|O-wSisCZgM2TwG3Src]|DhX@#!ql[-m');
define('AUTH_SALT',        'bNMqFZDKc^S7bWgqH~)fx5H@#lp|~SKgDAf&c_Uj|bcfm)u5OCEJf~kP<{(Rm*#^');
define('SECURE_AUTH_SALT', '7ZXtV?z+Vxx-h{wj.*y`kGgE-6T:F=?aM[di]]LiT[U;bI(=6A{5%9huHuhU@+?s');
define('LOGGED_IN_SALT',   'S%r.jw|q/D>u#,`#:>=QbMW1hj~z{uW/s$04,S||D,j-kLbs1YP[y+wDuo}5w_:#');
define('NONCE_SALT',       '7LK{t>5%g-ul/Hn`2:!Z`(ZKW8.pn-N|bGj4J-gMD??rp@.uKS_Rp||T$EpW8+bf');

/**#@-*/

/**
 * WordPress database table prefix.
 */
$table_prefix = 'wp7p_';

/** For developers: WordPress debugging mode. */
define('WP_DEBUG', false);

/* That's all, stop editing! Happy publishing. */

/** Absolute path to the WordPress directory. */
if (! defined('ABSPATH')) {
    define('ABSPATH', __DIR__ . '/');
}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
