"""
Apply ALT text to media via WP REST API using Application Password auth.

This script is SAFE by default: it will perform a dry-run unless you set APPLY=1 in the environment.

Usage (dry-run):
  WP_URL=https://loungenie.com/staging WP_USER=foo WP_APP_PASS=bar python scripts/apply_alt_via_rest.py

To actually perform updates set APPLY=1 in env (or pass --apply). Do NOT paste secrets in chat.

Behavior:
 - Reads artifacts/alt_wp_import.csv (generated by generate_wp_alt_payload.py)
 - For each row, attempts to find the media item by filename via the REST API
 - If found, will update the `meta.alt_text` or `alt_text` field depending on WP version
"""
import os
import csv
import requests
from urllib.parse import urljoin
from pathlib import Path

root = Path(__file__).resolve().parents[1]
artifacts = root / 'artifacts'
input_csv = artifacts / 'alt_wp_import.csv'

WP_URL = os.environ.get('WP_URL')
WP_USER = os.environ.get('WP_USER')
WP_APP_PASS = os.environ.get('WP_APP_PASS')
APPLY = os.environ.get('APPLY','0') in ('1','true','True')

if not input_csv.exists():
    print(f"Missing input: {input_csv} — run scripts/generate_wp_alt_payload.py first")
    raise SystemExit(1)

if not WP_URL or not WP_USER or not WP_APP_PASS:
    print("WP credentials not provided in env — running in discovery/dry-run mode only.")

session = requests.Session()
if WP_USER and WP_APP_PASS:
    session.auth = (WP_USER, WP_APP_PASS)
    session.headers.update({'User-Agent':'lg-sync-agent/1.0'})

def find_media_by_filename(filename):
    # Try several queries: search by filename, use media endpoint with search param
    if not WP_URL:
        return None
    media_url = urljoin(WP_URL, '/wp-json/wp/v2/media')
    params = {'search': filename}
    try:
        r = session.get(media_url, params=params, timeout=20)
        r.raise_for_status()
        items = r.json()
        for it in items:
            # match exact filename in source_url
            src = it.get('source_url','')
            if filename.lower() in src.lower():
                return it
        # fallback to first item
        if items:
            return items[0]
    except Exception as e:
        print(f"Error searching media for {filename}: {e}")
    return None

def update_media_alt(media_id, alt_text):
    if not WP_URL:
        print(f"Would update media {media_id} alt='{alt_text}' (no WP_URL configured)")
        return True
    update_url = urljoin(WP_URL, f'/wp-json/wp/v2/media/{media_id}')
    payload = {'alt_text': alt_text}
    try:
        if APPLY:
            r = session.post(update_url, json=payload, timeout=20)
            r.raise_for_status()
            print(f"Updated media {media_id} alt='{alt_text}'")
        else:
            print(f"DRY-RUN: would update media {media_id} alt='{alt_text}'")
        return True
    except Exception as e:
        print(f"Failed to update media {media_id}: {e}")
        return False

# Process CSV
with input_csv.open('r', encoding='utf-8', newline='') as fh:
    reader = csv.DictReader(fh)
    for row in reader:
        filename = row.get('filename','').strip()
        suggested = row.get('suggested_alt','').strip()
        url = row.get('image_url','').strip()
        if not filename or not suggested:
            continue
        media = find_media_by_filename(filename)
        if not media:
            print(f"No media found for {filename} (url={url})")
            continue
        media_id = media.get('id')
        print(f"Found media id={media_id} for {filename} (source_url={media.get('source_url')})")
        update_media_alt(media_id, suggested)

print("Done.")
