<#
cpanel-staging-setup.ps1

Create a MySQL database and user in cPanel using a cPanel API token, generate a secure DB password,
write a `staging-wp-config.php` filled with the DB values to the local folder, and optionally upload
that file to the staging site via FTP (if `FTP_*` environment variables are set).

ENV vars required:
  CPANEL_HOST   - e.g. loungenie.com
  CPANEL_USER   - cPanel username that owns the account
  CPANEL_TOKEN  - cPanel API token (preferred)

Optional (to upload file via FTP):
  FTP_HOST, FTP_USER, FTP_PASS, FTP_DEST_DIR (default: /public_html/staging_loungenie)

Usage (run locally):
  $env:CPANEL_HOST='loungenie.com'
  $env:CPANEL_USER='pools425'
  $env:CPANEL_TOKEN='(paste token here)'
  powershell -ExecutionPolicy Bypass -File .\scripts\cpanel-staging-setup.ps1

Security:
 - The script will not echo the API token. It writes DB credentials to `staging-db-credentials.json` in the
   current directory with restricted file permissions.
#>

param(
    [string]$CPANEL_HOST_PARAM,
    [string]$CPANEL_USER_PARAM,
    [string]$CPANEL_TOKEN_PARAM,
    [string]$FTP_HOST_PARAM,
    [string]$FTP_USER_PARAM,
    [string]$FTP_PASS_PARAM,
    [string]$FTP_DEST_DIR_PARAM
)

function Abort($msg){ Write-Error $msg; exit 1 }

$cpHost = if ($CPANEL_HOST_PARAM) { $CPANEL_HOST_PARAM } else { $env:CPANEL_HOST }
$user = if ($CPANEL_USER_PARAM) { $CPANEL_USER_PARAM } else { $env:CPANEL_USER }
$token = if ($CPANEL_TOKEN_PARAM) { $CPANEL_TOKEN_PARAM } else { $env:CPANEL_TOKEN }

if (-not $cpHost) { Abort 'Set CPANEL_HOST environment variable.' }
if (-not $user) { Abort 'Set CPANEL_USER environment variable.' }
if (-not $token) { Abort 'Set CPANEL_TOKEN environment variable.' }

$baseUrl = "https://$cpHost:2083"
$headers = @{ Authorization = "cpanel ${user}:${token}" }
Write-Host "Params: CPANEL_HOST_PARAM='$CPANEL_HOST_PARAM' CPANEL_USER_PARAM='$CPANEL_USER_PARAM' CPANEL_TOKEN_PARAM='(hidden)'."
Write-Host "Using cPanel host: '$cpHost' -> baseUrl=$baseUrl"

# Helpers
function UApiGet([string]$endpoint){
    $url = 'https://' + $cpHost + ':2083/execute/' + $endpoint
    try {
        return Invoke-RestMethod -Uri $url -Headers $headers -Method Get -SkipCertificateCheck
    } catch {
        Throw "UAPI call failed: $endpoint -- $_"
    }
}

# Generate DB name/user (cPanel DB names are prefixed by account; to be safe, use short names)
$ts = Get-Date -Format "yyMMddHHmm"
$dbShort = "loungenie_stg_$ts"
$dbUser = "loungenie_u_$ts"
# Generate a secure password
function New-SecurePassword($length=20){
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $bytes = New-Object 'Byte[]' $length
    $rng.GetBytes($bytes)
    $str = [System.Convert]::ToBase64String($bytes) -replace '[+/=]', ''
    return $str.Substring(0, [Math]::Min($length, $str.Length))
}
$dbPass = New-SecurePassword 24

Write-Host "Creating database '$dbShort'..."
$respDb = UApiGet("Mysql/create_database?name=$dbShort")
if ($respDb.status -ne 1) { Abort "Failed to create database: $($respDb)" }
Write-Host "Database created. Creating DB user '$dbUser'..."
$respUser = UApiGet("Mysql/create_user?name=$dbUser&password=$([uri]::EscapeDataString($dbPass))")
if ($respUser.status -ne 1) { Abort "Failed to create DB user: $($respUser)" }

Write-Host "Granting privileges to user on database..."
$privResp = UApiGet("Mysql/set_privileges_on_database?user=$dbUser&database=$dbShort&privileges=ALL%20PRIVILEGES")
if ($privResp.status -ne 1) { Abort "Failed to set privileges: $($privResp)" }

# Save credentials locally (restrict permissions)
$creds = @{ database = $dbShort; db_user = $dbUser; db_pass = $dbPass; host = 'localhost' }
$credsJson = $creds | ConvertTo-Json -Depth 3
$credFile = Join-Path -Path (Get-Location) -ChildPath 'staging-db-credentials.json'
Set-Content -Path $credFile -Value $credsJson -Force
# Restrict file permissions to current user
try {
    icacls $credFile /inheritance:r | Out-Null
    icacls $credFile /grant:r "$($env:USERNAME):(R,W)" | Out-Null
} catch { Write-Warning "Could not adjust file ACLs: $_" }
Write-Host "Wrote DB credentials to $credFile"

# Create wp-config content (basic minimal)
$wpConfig = @"
<?php
// Auto-generated by cpanel-staging-setup.ps1
define('DB_NAME', '$($creds.database)');
define('DB_USER', '$($creds.db_user)');
define('DB_PASSWORD', '$($creds.db_pass)');
define('DB_HOST', 'localhost');
define('DB_CHARSET', 'utf8mb4');
define('DB_COLLATE', '');

// Authentication keys and salts - keep these unique and secret
define('AUTH_KEY',         'put your unique phrase here');
define('SECURE_AUTH_KEY',  'put your unique phrase here');
define('LOGGED_IN_KEY',    'put your unique phrase here');
define('NONCE_KEY',        'put your unique phrase here');
define('AUTH_SALT',        'put your unique phrase here');
define('SECURE_AUTH_SALT', 'put your unique phrase here');
define('LOGGED_IN_SALT',   'put your unique phrase here');
define('NONCE_SALT',       'put your unique phrase here');

$table_prefix = 'wp_';

if ( !defined('ABSPATH') )
    define('ABSPATH', dirname(__FILE__) . '/');

require_once ABSPATH . 'wp-settings.php';
"@

$wpFile = Join-Path -Path (Get-Location) -ChildPath 'staging-wp-config.php'
Set-Content -Path $wpFile -Value $wpConfig -Force
Write-Host "Wrote local file: $wpFile"

# Optional FTP upload if FTP_* env vars exist
$ftpHost = if ($FTP_HOST_PARAM) { $FTP_HOST_PARAM } else { $env:FTP_HOST }
$ftpUser = if ($FTP_USER_PARAM) { $FTP_USER_PARAM } else { $env:FTP_USER }
$ftpPass = if ($FTP_PASS_PARAM) { $FTP_PASS_PARAM } else { $env:FTP_PASS }
$ftpDestDir = if ($FTP_DEST_DIR_PARAM) { $FTP_DEST_DIR_PARAM } else { $env:FTP_DEST_DIR }
if (-not $ftpDestDir){ $ftpDestDir = '/public_html/staging_loungenie' }

if ($ftpHost -and $ftpUser -and $ftpPass) {
    Write-Host "Detected FTP credentials - attempting to upload staging-wp-config.php to ${ftpHost}${ftpDestDir}/wp-config.php"
    try {
        # Build FTP URI (passive)
        $uri = "ftp://$ftpHost$ftpDestDir/wp-config.php"
        $wc = New-Object System.Net.WebClient
        $wc.Credentials = New-Object System.Net.NetworkCredential($ftpUser,$ftpPass)
        $wc.UploadFile($uri, 'STOR', $wpFile)
        Write-Host "Uploaded wp-config.php to $uri"
    } catch {
        Write-Warning "FTP upload failed: $_"
    }
} else {
    Write-Host "FTP credentials not found in env - skipping automatic upload. You can upload $wpFile to your staging WordPress root manually."
}

Write-Host "Done. Database: $($creds.database)  DB user: $($creds.db_user)"
Write-Host "Keep the file staging-db-credentials.json secure and remove it after use."
